package com.dynamica.alaport;



import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.dynamica.alaport.R;

import java.util.ArrayList;


/**
 * A simple {@link Fragment} subclass.
 */
public class HistoryFragment extends Fragment {
    RecyclerView rec;
    ArrayList<ArrayList<String>> aa;
    public HistoryFragment() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view=inflater.inflate(R.layout.fragment_history, container, false);
        rec=(RecyclerView) view.findViewById(R.id.hisRec);
        aa=new ArrayList<>();
        setLang();
        RecyclerView.LayoutManager mLayoutManager=new LinearLayoutManager(getActivity());
        rec.setLayoutManager(mLayoutManager);
        rec.setItemAnimator(new DefaultItemAnimator());
        rec.setAdapter(new HistoryAdapter(aa, getActivity()));
        return view;
    }
    public void setLang(){
        switch(((AlaportInfoActivity)getActivity()).lang){
            case "K":
                aa.add(new ArrayList<String>());aa.get(0).add("1935");aa.get(0).add("Алматы әуежайы 1935 жылы қолданысқа берілді.");
                aa.add(new ArrayList<String>());aa.get(1).add("1991");aa.get(1).add("1991 жылғы 26 сәуірде «Алма-Ата аэропорты» болып қайта құрылды. 1993 жылдан бері дербес құрылымдық бірлік болып саналады. 1994 жылы ол «Алматы аэропорты» болып өзгертіліп, оның қызметін өзінің құқықтық мұрагері - «Халықаралық Алматы әуежайы» АҚ жалғастырды.");
                aa.add(new ArrayList<String>());aa.get(2).add("2000");aa.get(2).add("2000 жылы Халықаралық Алматы әуежайының жүк тасымалдаудағы алғашқы серіктесі болып сол кездері аптасына екі рет Boeing 747 ұшақтарымен ұшатын EL-AL авикомпаниясы атанды. Әуежайдың геосаяси тұрғыдан тиімді орналасуын және техникалық дайындық деңгейін бағалай келе, EL-AL авикомпаниясы Алматы арқылы ұшатын өз рейстерін көбейтуді ұйғарды. Бүгінгі күні EL-AL авикомпаниясы Алматы әуежайына аптасына 10-12 рейс жасайды.");
                aa.add(new ArrayList<String>());aa.get(3).add("2003");aa.get(3).add("2003 жылы Алматы әуежайы арқылы жолаушылар тасымалдауларын ғана жүзеге асырып жүрген атақты KLM авиакомпаниясының жүк тасымалдау бөлімі аптасына 6 рет жиілікпен ұшатын жаңа рейстерін ашты. ");
                aa.add(new ArrayList<String>());aa.get(4).add("2003");aa.get(4).add("Сол 2003 жылдың соңында аптасына 4 рет ұшып, атақты FedEx авиакомпаниясы Халықаралық Алматы әуежайының серіктесі ретінде танылды. 2005 жылдың 01 наурызынан FedEx авиакомпаниясы бір айда орындалатын рейстерінің санын 50-ге дейін арттырып, Гонконг-Алматы-Париж және Шанхай-Алматы-Франкфурт бағыттары бойынша ұша бастады. " + "\n" + "Алматы әуежайында бір уақытта FedEx авиакомпаниясының екі ұшағы тұрақтанады. Олар жүкті бір ұшақтан екінші ұшаққа тиеу жұмыстарын атқарады. Мұндай операция авиакомпания үшін өте ыңғайлы болмақ, ол жүкті бір нүктеден екінші нүктеге жедел түрде жеткізіп, әуе кемелері ресурстарын үнемдеуге мүмкіндік береді. Болашақта FedEx авиакомпаниясы өз ұшақтарына Халықаралық Алматы әуежайындағы А-чек бағдарламасы бойынша жедел қызмет түрін пайдалануды жоспарлап отыр. Жазғы кезеңде А-чек қызметі тікелей ӘК тұрақтарында жүзеге асырылса, қыста жабдықталған ангар кешенінің қызметі ұсынылады.");
                aa.add(new ArrayList<String>());aa.get(5).add("2004");aa.get(5).add("2004 жылдан бері Халықаралық Алматы әуежайы қызметтерін Lufthansa Cargo және Asiana авиакомпаниялары пайдаланады. Осы жылдары Алматы әуежайына ресейлік ірі жүк тасымалдаушылар – Волга-Днепр және Антонов авиажолдары компаниялары да келді. Олар өз рейстерін әлемдегі ең үлкен әуе кемелері санатына жататын әйгілі Ан-124 <Руслан> және Ан-225 <Мaрия> ұшақтарымен орындайды. \n" + "2004 жылдың желтоқсан айында жаңа жолаушылар терминалы іске қосылды. Авиажолаушылардың талап-тілектерін қанағаттандыру мақсатында жаңа жолаушылар терминалында адам өміріне қажетті барлық жүйелер, қазіргі заманғы бақылау жүйелері, ғимаратты басқару жүйесі, орындалған авиарейстер туралы ақпарат беру жүйелері, ішкі және сыртқы бейнебақылау жүйелері, жолаушыларды құлақтандыру жүйелері, жүкті іздестіру жүйелері орнатылды.\n"+"2005 жылдың қаңтар айынан бастап американдық Polar Air Cargo авиакомпаниясы Atlas авиакомпаниясымен біріге отырып, Алматы әуежайын Шанхай – Алматы – Амстердам бағытындағы рейстерін орындау мақсатында пайдалана бастады. Ұшудың жиілігі аптасына 7-ге дейін артты.\n 2005 жылдың ақпан айынан бастап итальяндық Ocean Airlines авиакомпаниясы Халықаралық Алматы әуежайына қонып, оның техникалық қызметтерін пайдаланатын болды. Бұл авиакомпаниямен Брешия – Алматы – Гонконг, Брешия – Алматы – Шанхай бағыттары бойынша Боинг 747-200 әуе кемесімен аптасына 4 рет ары –бері ұшатын рейстер орындалады. \n" + "\n" + "2005 жылғы тамыз айының соңында Cargolux компаниясы Алматы арқылы Гонконг – Алматы – Баку – Люксембург және Люксембург – Гонконг – Алматы – Люксембург бағыты бойынша Боинг 747-200 әуе кемесімен аптасына 3 рет жүзеге асырылатын ұшу кестесін іске қосты." + "\n" + "2005 жылғы қараша айынан China Easter Airlines компаниясының Шеньжень – Алматы – Люксембург бағыты бойынша Боинг 747-200 әуе кемесімен аптасына 4 рет ұшатын рейстері орындала бастады.");
                aa.add(new ArrayList<String>());aa.get(6).add("2006");aa.get(6).add("2006 жылдың маусым айында FedEx компаниясы мен Қазақстан Республикасының Үкіметі арасында авиакомпаниялар қызметінің аясын жетінші «әуе еркіндігіне» дейін кеңейтуге мүмкіндік беретін әуе қатынастары келісіміне қол қойылды." + "\n" + "2006 жылдың шілде айында Malaysia Airlines компаниясы Куала-Лумпур-Шанхай-Амстердам бағыты бойынша Боинг 747-200 әуе кемесімен аптасына 4 рет орындалатын рейстерін ашты.");
                aa.add(new ArrayList<String>());aa.get(7).add("2007");aa.get(7).add("2007 жылдың маусымынан бастап бизнес терминал іске қосылды. Сәулеттік және тарихи мәні зор және қала сәулетінің бірегей ескерткіші болып саналатын ғимарат жаңадан қалпына келтірілді. Ғимараттың дизайн жұмыстарына итальяндық сәулетші жетекшілік жасады. Ол интерьердің стильдік сәйкестігі мен реңдік үйлесімінің дұрыс шешімін табу арқылы қайталанбас жайлы атмосфера құра білді. Бизнес терминалда чартелік рейс жолаушыларына қызмет көрсетіледі. Терминалдың залдарында жолаушыларға өздерінің іскерлік шаруаларын жүзеге асыруға қажетті қызмет түрлері де ұсынылады: келіссөздер жүргізу, пресс-конференциялар өткізу. Жолаушыларға Duty Free дүкені, ассортименті бай шағын бар қызмет көрсетеді. Жайлы интерьер, жоғары деңгейлі техникалық жабдықтар." + "\n" + "Қазіргі уақытта Алматы әуежайында коммерциялық құқыққа ие Turkish Airlines, MNG Airlines, MY Cargo, MK Airlines секілді авиакомпаниялар өздерінің жүк тасымалдау рейстерін орындауда. " + "\n" + "Жүргізілген келіссөздердің арқасында 2007 жылы Алматы әуежайына әлемге әйгілі американдық UPS компаниясының ұшақтары жүйелі түрде ұша бастады. Сондай-ақ, қытайдың Yangtze River Express авиакомпаниясы өзінің ұшу бағдарламасын бастауға ниет білдіріп отыр.");
                break;
            case "E":
                aa.add(new ArrayList<String>());aa.get(0).add("1935");aa.get(0).add("The airport was founded in 1935.");
                aa.add(new ArrayList<String>());aa.get(1).add("1991");aa.get(1).add("Up to 1990 it was the part of Kazakh Department of Civil Aviation. On April 26, 1991, the airport was re-organized into Alma-Ata Airport, and since 1993 it runs as an independent business unit. In 1994, it was re-organized into Almaty Airport OJSC, and later re-named to Almaty International Airport JSC. ");
                aa.add(new ArrayList<String>());aa.get(2).add("2000");aa.get(2).add("In 2000, the first cargo partner of Almaty International Airport was EL-AL Israel Airlines operating at that time two flights per week on Boeing 747. Gradually, estimating the perspective of geopolitical location of the airport and its growing technical level, the EL AL increased number of its operations.");
                aa.add(new ArrayList<String>());aa.get(3).add("2002");aa.get(3).add("In December 2002, Almaty airport began fog dispersal operation by way of artificial seeding of the freezing fog using the liquid nitrogen.\n" + "The method consists in lowering the air temperature to the levels that lead to crystallization of the moisture in the fog because of the deep and rapid drop in the air temperature. A significant drop in the air temperature is provided by dispersing of liquid nitrogen with the help of a ground generator of the ice small dispersed particles.");
                aa.add(new ArrayList<String>());aa.get(4).add("2003");aa.get(4).add("In early 2003, following the passenger services, the cargo subdivision of the known KLM began operating 6 flights per week to Almaty airport.\n" + "At the end of the same year, the equally well-known FedEx became a partner of Almaty International Airport operating 4 flights per week. Since March 1, 2005, FedEx has increased frequency of operations up to 50 flights per month, and has begun performing the flights en route Hong Kong – Almaty – Paris, and Shanghai – Almaty – Frankfurt.\n" + "Almaty airport can accommodate two FedEx’s aircraft simultaneously. They unload the cargo from one aircraft and load onto another. Such operation is very favorable for the airline, as it enables to expedite the cargo delivery from one point to another, and save resource of aircraft. In prospect, FedEx plans to get the line maintenance under the program A-check for its aircraft at Almaty International Airport. During the summer period A-check is directly performed at an aircraft parking area, and during the winter period it is performed at an equipped hangar complex.");
                aa.add(new ArrayList<String>());aa.get(5).add("2004");aa.get(5).add("In 2004, Lufthansa Cargo and Asiana came to Almaty International Airport. During the same period, Russia’s largest cargo carriers Volga-Dnepr and Antonov Airlines began operating the flights on the famous An-124 Ruslan and An-225 Mriya, the largest aircraft in the world.\n" + "In December 2004, a new passenger terminal was opened. To satisfy passenger needs, the passenger terminal is equipped with the up-to-date life support system, building management system, flight information system, interior and exterior video surveillance system, public address system, lost and found system, etc.\n" + "In January 2005, an American airline Polar Air Cargo together with Atlas began using the Almaty airport for flights en route Shanghai – Almaty – Amsterdam, increasing the frequency up to 7 flights per week.\n" + "In February 2005, Ocean Airlines, an Italian airline, began operating the flights with technical landing at Almaty International Airport. The airline operates Boeing 747-200 en route Brescia – Almaty – Hong Kong, Brescia – Almaty – Shanghai and back 4 times per week.\n" + "At the end of August, 2005, Cargolux launched a flight program via Almaty en route Hong Kong – Almaty – Baku – Luxemburg, and Luxemburg – Hong Kong – Almaty – Luxemburg on Boeing 747-200, 3 times per week.\n" + "In November 2005, China Easter Airlines began operating the flights en route Shenzhen – Almaty – Luxemburg 4 times per week on Boeing 747-200.");
                aa.add(new ArrayList<String>());aa.get(6).add("2006");aa.get(6).add("In June 2006, the air service agreement was concluded between FedEx and Government of the Republic of Kazakhstan significantly expanding the scope of the airline’s activity up to the seventh freedom of the air.\n" + "In July 2006, Malaysia Airlines began operating the Boeing 747-200 en route Kuala Lumpur – Shanghai – Almaty – Amsterdam 4 times per week.");
                aa.add(new ArrayList<String>());aa.get(7).add("2007");aa.get(7).add("In June 2007, business terminal opened its doors. The refurbished building which is a unique urban architecture monument has an architectural historic significance. Design works were managed by Italian architect, and by means of style conformity of interior elements and coloristic solutions he was succeed in creating the specific comfort and cosiness atmosphere. The business terminal specializes in passenger service of charter flights. In business terminal lounges passengers can receive a wide range of business services: conduct negotiations, and hold press-conferences. Duty Free shop, wide assortment of bar, cozy interior and high technical equipment are available for passengers.\n" + "Currently, such airlines as Turkish Airlines, MNG Airlines, MY Cargo, and MK Airlines operate cargo flights with traffic rights to Almaty airport.\n" + "Based on the negotiations, in 2007, UPS, the world famous American airline, began operating the scheduled flights to Almaty airport. And Yangtze River Express, a Chinese airline, expressed its intention to launch a flight program as well.");
                break;
            default:
                aa.add(new ArrayList<String>());aa.get(0).add("1935");aa.get(0).add("Аэропорт был создан");
                aa.add(new ArrayList<String>());aa.get(1).add("1991");aa.get(1).add("входил в состав КУГА (Казахского " + "Управления Гражданской Авиации). " + "26 апреля 1991 года реорганизован " + "в \"Аэропорт Алма-Ата\". С 1993 года " + "- самостоятельная структурная " + "единица. В 1994 году преобразован " + "в АООТ \"Аэропорт Алматы\", " + "правопреемником которого " + "является в настоящее время АО " + "\"Международный аэропорт " + "Алматы\".");
                aa.add(new ArrayList<String>());aa.get(2).add("2000");aa.get(2).add("В 2000 году первым партнером " + "Международного Аэропорта " + "Алматы по грузоперевозкам стала " + "авиакомпания EL-AL, совершавшая " + "тогда два рейса в неделю на " + "самолетах Boeing 747. Постепенно, " + "оценивая перспективность " + "геополитического расположения " + "аэропорта и его растущий " + "технический уровень, авиакомпания " + "EL-AL увеличивала количество " + "рейсов.");
                aa.add(new ArrayList<String>());aa.get(3).add("2002");aa.get(3).add("С декабря 2002 года в алматинском " + "аэропорту начаты практические " + "работы по рассеиванию туманов " + "методом искусственного " + "рассеивания переохлажденных " + "туманов с использованием жидкого " + "азота." + "\n" + "Метод заключается в понижении " + "температуры воздуха до значений, " + "приводящих к кристаллизации влаги " + "в тумане за счет глубокого и " + "быстрого понижения температуры " + "воздуха. Значительное понижение " + "температуры воздуха " + "обеспечивается распылением " + "жидкого азота наземным " + "генератором мелкодисперсных " + "частиц льда");
                aa.add(new ArrayList<String>());aa.get(4).add("2003");aa.get(4).add("В начале 2003 года вслед за " + "пассажирскими перевозками, в " + "аэропорт Алматы начало полеты " + "грузовое отделение известной " + "авиакомпании KLM, с регулярностью " + "- 6 раз в неделю. ");
                aa.add(new ArrayList<String>());aa.get(5).add("2004");aa.get(5).add("В 2004 году в Международный " + "Аэропорт Алматы пришли " + "авиакомпании Lufthansa Cargo и " + "Asiana. В этот же период стали " + "совершать рейсы крупнейшие " + "российские грузоперевозчики " + "Волга-Днепр и Авиалинии Антонова " + "на знаменитых Ан-124 <Руслан> и " + "Ан-225 <Мaрия> - самом большом " + "самолете в мире. ");
                aa.add(new ArrayList<String>());aa.get(6).add("2006");aa.get(6).add("В июне 2006 года подписано " + "соглашение о воздушном " + "сообщении между компанией FedEx " + "и правительством Республики " + "Казахстан, значительно " + "расширяющее сферу деятельности " + "авиакомпании, вплоть до седьмой " + "<свободы воздуха>. " + "\n" + "С июля 2006 года компания Malaysia " + "Airlines начала полеты на Boeing " + "747-200 по маршруту Куала-Лумпур " + "- Шанхай - Алматы - Амстердам с " + "регулярностью 4 раза в неделю. ");
                aa.add(new ArrayList<String>());aa.get(7).add("2007");aa.get(7).add("С июня 2007 года открыл свои " + "двери бизнес терминал. " + "Отреставрированное здание имеет " + "архитектурно- исторические " + "значение, восстановлен уникальный " + "памятник городской архитектуры. " + "Дизайнерскими работами " + "руководил итальянский архитектор, " + "путем стилевого соответствия " + "деталей интерьера и " + "колористических решений, ему " + "удалось создать неповторимую " + "атмосферу комфорта и уюта. Бизнес " + "терминал специализируется на " + "обслуживании пассажиров " + "чартерных рейсов. В залах " + "терминала пассажиры могут " + "получить широкий спектр деловых " + "услуг: проводить переговоры, пресс-" + "конференции. К услугам пассажиров " + "- магазин Duty Free, богатый " + "ассортимент бара. Уютный " + "интерьер, высокая техническая " + "оснащенность." + "\n" + "В настоящее время такие " + "авиакомпании как Turkish Airlines, " + "MNG Airlines, MY Cargo, MK Airlines " + "выполняют в аэропорт Алматы " + "грузовые рейсы с коммерческими " + "правами. " + "\n" + "На основании проведенных " + "переговоров, в 2007 году в аэропорт " + "Алматы начинает выполнять " + "регулярные рейсы американская " + "компания UPS, известная по всему " + "миру. Так же изъявила свое " + "намерение начать программу " + "полетов китайская авиакомпания " + "Yangtze River Express.");
                break;
        }
    }

}
